# contador = 1

# while contador <=5:
#     print(contador)
#     contador += 1



# numero_secreto = 7
# adivinha = int(input('Adivinha o numero (entre 1 e 10)'))

# while adivinha != numero_secreto:
#     print('Errado,tente novamente!!')
#     adivinha =int(input('Adivinhe o numero(1 a 10)'))
# print('Parabens! voce adiviou o numero secreto')


# numeros = [1,2,3,4,5,6,7,8,9,]
# numero_procurado = 9
# index = 0


# while index <len(numeros):
#     if numeros[index] == numero_procurado:
#         print(F'encontramos o Numero {numero_procurado}')
#         break
#     print(numeros[index])
#     index+=1



# frase = 'Programar e muiTo maneiro'
# letra_procurada = 'T'
# index = 0


# while index < len(frase):
#     if frase[index] == letra_procurada:
#         print(F'encontramos a letra procurada {letra_procurada}')
#         break
#     index +=1
# else:print(f'nao encontramos a letra {letra_procurada} na lista')




# numero_secreto =random.randint(1, 10)
# tentativas_maximas = 3
# tentativas = 0

# print('Bem-Vindo ao jogo de adivinhaçao')
# print('Voce tem que adivinhar um numero Enre 1 e 10')

# while tentativas < tentativas_maximas:
#     tentativas = int(input('Digite a sua tentiva:'))
#     tentativas += 1
# if tentativas == numero_secreto:
#     print('Voce acertou Numero Parabens')
#     break
# elif tentativas < numero_secreto:
#     print('O numero secreto e maior')
#     else:
#     print('O numero secreto e menor. tente novamente')
# else:
#         print('O numero secreto e menor. tente novamente')


# contador = 1
# while contador <=5:
#     print(contador)
#     contador += 1


# soma = 0
# numero = 1
# while numero <=10:
#     soma += numero
#     numero +=1
#     print('A soma dos numeros de 1 a 10 é:',soma)


# senha = ""
# while senha != "1234":
#     senha = input('Digite a senha')
#     print('senha Coreta')


# contagem = 1
# while contagem <=10:
#     print(contagem)
#     contagem +=1
# print('o numero foi contado de 0 a 10')



# contagem = 1
# soma = 0
# while contagem <=100:
#     soma += contagem
#     contagem += 1
#     print(contagem)


# numero = 11

# while numero >=1:
#     numero -=1
#     print(numero)


# contador = 0
# limite = 10
# while contador < limite:
#     print(contador)
#     contador +=1


# senha = int(input('Digite sua Senha'))
# while senha != "12345":
#     senha = input("digite sua senha")
#     if senha == "12345":
#         print('Acesso concendido')
#     else:
#         print('Senha incorreta')



# opçao = ''
# while opçao != "sair":
#     print('Menu')
#     print('1. opçao 1')
#     print('2. Opçao 2')
#     print('Digite sair Para Encerrar')
#     opçao =input('Escolha uma opçao')
#     if opçao == '1':
#         print('Voce escolheu opçao 1')
#     elif opçao == '2':
#         print('Voce escolheu a opçao 2')
#     elif opçao == 'sair':
#         print('Voce escolheu a opçao sair')
#     else:
#         print('Opçao invalida ,tente novamente!')


# limite = float(input('Digite um Numero'))
# base =0

# while base <= limite:
#     print(base)
#     base +=1
#     if base / 1 == 1

# contador = 1
# while contador <= 5:
#     print(contador)
#     contador +=1



# numero_secreto = 7
# adivinha = int(input('Adivinhe o Numero secreto de (1 á 10)          '))

# while adivinha != numero_secreto:
#     print('Voce esta errado')
#     adivinha = int(input('Adivinhe 1 a 10               '           ))
# print('Voce acertou!')    


# numeros = [1, 2, 3, 5, 6, 7, 8,9]
# numero_procurado = 5
# index = 0

# while index < len(numeros):
#     if numeros[index] == numero_procurado:
#         print(f' Encontramos o Numero {numero_procurado}')
#         break
#     print(numeros[index])
#     index +=1

# frase = 'programar  e muito maneiro'
# letra_procurada =  'b'
# index = 0

# while index <len(frase):
#     if frase[index] == letra_procurada:
#         print(f' Encontramos a letra procurada        {letra_procurada}')
#         break
#     index += 1
# else:
#     print(f' nao encomtramos a letra procurada {letra_procurada}')


# import random
# numero_secreto = random.randint(1, 10)

# tentativas_maximas = 3
# tentativas = 0

# print('Bem Vindo ao jogo de adivinhçao')
# print('Voce tem que adivinhar um numero entre (1 a 10)')
# while  tentativas < tentativas_maximas:
#     tentativas = int(input('Digite sua tentativa'))
#     tentativas += 1
        
#     if tentativas == numero_secreto:
#         print(f'Voce achou o Numero Secreto Parabéns    {numero_secreto}')
#         break
#     elif tentativas < numero_secreto:
#         print('O numero e um pouco maior')
#     else:
#         print('O numero e um pouco menor')
# else:
#     print(f' FIM DAS TENTATIVAS VOCE ATINGIU O MAXIMO {tentativas_maximas}')

# print(f'O JOGO ACABOU MEU AMIGO!!! NUMERO SECRETO ERA {numero_secreto}')




# pergunta = ''

# while pergunta != 'nao':
#     pergunta = input('Deseja continuar?')
#     if pergunta == 'a':
#         print('Voce continua no game!!')
# else:
#     print('Voce parou o game')

# while True:

#     nota =  [1,2,3,4,5,6,7,8,9,10]
#     nota = float(input('Digite o valor da Nota'))
#     if nota <=0:
#         print(f' a nota que vc aprensentou e {nota} ela e invalida')
#     elif nota >= 11:
#         print(f'{nota} A nota e invalida')
#     else:
#         print(f'{nota}a nota e Valida parabens!!!')
#         break



# cadastro1 = '123'
# cadastro2 =  '456'

# while cadastro2 != cadastro1:
#     cadastro1 = input('Digite login e senha')
#     cadastro2 = input('Digite a Senha')
#     if cadastro1 == cadastro2 and cadastro2 == cadastro1:
#         print('A login nao pode ser Igual a senha')
#     elif cadastro1 != cadastro2 and cadastro2 != cadastro1:
#         print('Cadastro Feito com Sucesso')
#         break
# else:
#     ('Ocorreu algum Erro Revise as informaçoes por favor')


# numero = int(input('Digite o numero'))
# while numero >=0:
#         print(numero)
#         numero -=1
  

# soma = 0
# numero = int(input('Digite um Numero'))
# while numero >=0:
#         soma +=numero
#         numero= int(input('Digite Um numero Positivo(Digite um Numero negativo para Encerar)'))
#         print(f' a soma dos numero digityados é {soma}')
       

# numero = int(input('digite um numero para exibit a tabuada'))
# i = 1
# while i <=10:
#         print(f'{numero} x {i} ={numero*i}')
#         i += 1


# usuario_correto = 'admin'
# senha_correta =  123

# while True:
#         usuario = input('Digite o nome de usuario')
#         senha = int(input('Digite a senha contendo apenas Numeros'))
#         if usuario == usuario_correto and senha == senha_correta:
#                 print('Acesso Concedido')
#                 break
#         else:
#                 print('Nome de usuario ou senha incorretos . tente novamente')



# nota1 =float(input('Digite a primeira nota (entre 0 e 10)'))
# nota2 = float(input('Digite a primeira nota (entre 0 e 10)'))
# resultado = nota1+nota2 /2

# while resultado <=0:
        
#         print(resultado)