# for contador in range(0,5):
#     print(contador)

# for i in range (1,12,2):
#     print(i)

# frase = 'python'
# for letra in frase:
#     print(letra)

# frase = 'Bem-Vindo(a) ao Mundo python'
# contagem = 0
# for i in frase:
#     if i == 'a':
#         contagem +=1
#         print(f' A letra a apareceu {contagem} vezes na frase')


# for numero in range(1,11):
#     print(numero)
#     if  numero== 5:
#         break


# contagem = 0
# palavra = 'passarinho'
# for i in palavra:
#     if i == 's':
#         contagem +=1
#         print(f'as Letras S forao encontradas {contagem} VEZES')
        

# for numero in range(1,11):
#     if  numero  %2 == 0:
#         continue
#     print(numero)


# for i in range(0,11):
#     print(i)


# tabuada = 7
# for i in range(1,11):
#     print(f'{tabuada} x {i} = {tabuada*i}')
            



# for i in range(1,11):
#     print(f'O quadrado de {i} é  {i**2}')




# palavra = input('Digite uma string')

# for i in palavra:
#         print(i)



# vogais = 0
# palavras = input('Digite a palavra pra saber quantas Vogais existem')
# for i in palavras:
#     if i in 'a,e,i,o,u':
#         vogais +=1
# print(f' existe  {vogais} VOGAIS  Nessa palavra ////{palavras} !!!')



# contagem = 0
# palavra = input('Digite um palavra eu direi quantas Vezes a Letra (i) Aparece ((lixo!))')

# for i in palavra:
#         if i in 'i':
#             contagem +=1
# print(f' a Palavra tem {contagem} i seu animal Filho da puta!!!!')
# contagem =0
# palavra = input('Digite a palavra que Voce deseja       ')
# vogal = input('Digite a Vogal que Voce deseja na palavra         ')

# for i in palavra:
#         if i in vogal:
#             contagem +=1
# print(f' {palavra}Palavra tem {contagem}  vogal !!!!')





# palavra = input('Digite a Palavra que deseja      ')
# consoante = 'a,e,i,o,u'

# for i in palavra:
#     if i not in consoante:
#         break
# print(f' a primeira consoante a ser mostrada é {i}')




# numeros = '1,2,3,4,5,6,7,8,9'

# for numeros in range(1,8):
#     print(numeros)


# palavra = input('DIGITE A PALAVRA')
# vogais = 'aeiou'
# for i in palavra:
#     if i in 'aeiou':
#         continue
#     print(i)



# for i in range(1,11):
#     if i % 4 ==0:
#         continue
#     print(f'{i} tabuada é {i*7} ')



# for i in range(1,21):
#     if i %3 !=0:
#         continue
#     print(i)


# nota2 = float(input('Digite a nota do primeiro'))
# nota1 = float(input('Digite a nota do segundo'))
# nota3 = float(input('Digite a nota do terceiro'))
# resultado = nota1+nota2
# for i in resultado:
#     resultado = float
#     if resultado / 2:
#         print(resultado)


# soma = 0
# for i in range(0,2):
#     nota = float(input(' digite a nota '))
#     soma = soma +nota
# media = soma/2
# print(f' a media das nota é {media}')


# soma = 0
# for i in range(0,5):
#     valores = int(input(f'Digite o {i+1} para ser somado'))
#     soma = soma + valores
# print(f' a soma dos numeros é {soma}')


# n = int(input('Digite um numero para mostra os inteiros de 1 a n'))
# for i in range(1,n+1):
#     print(i)

# for i in range(1,11):
#     print(f' os quadrados de {i} e {i**2}')


# palavra = input('Digite a palavra')
# palavra_substituida = ''
# for i in palavra:
#         if i in 'abcde':
#             palavra_substituida +='*'
#         else:
#             palavra_substituida +=i
# print(f' a palavra subtituida é {palavra_substituida}')


# frase = input('Digite a frase')
# palavra =  ''
# for i in frase:
#         if i in '.!?':
#             print(palavra)
#             palavra = ''
#         else:
#             palavra +=i
