# minha_lista = ['elemento1', 'elemento2', 'elemento3',]
# print(minha_lista[0])


# minha_lista = [10,20,30,40,50]
# print(minha_lista[0])


# minha_lista = [10,20,30,40,50]
# print(minha_lista[2])



# minha_lista = [10,20,30]
# minha_lista[1]= 200
# print(minha_lista)


# minha_lista = [1,2,3]
# minha_lista.append(4)
# print(minha_lista)
# minha_lista.insert(1,'a')
# print(minha_lista)



# minha_lista =[1,2,3,4,5]
# minha_lista.remove(3)
# print(minha_lista)
# minha_lista.pop(1)
# print(minha_lista)
# minha_lista.clear
# print(minha_lista)



# meus_brinquedos =['carro','boneca','bola']
# tamanho =len(meus_brinquedos)
# print(tamanho)


# frutas= ['maça','banana', 'cereja']
# for fruta in frutas:
#     print(fruta)


# nome = ['thiago','pedro','joao']
# for i in nome:
#     comprimento =  len(i)
#     print(f'Ola {i} seu nome e tem {comprimento} de comprimento de letras')


